CRS/Models/ErrorViewModel.cs
namespace CRS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRS/Models/Respuesta/Respuesta.cs
namespace CRS.Models.Respuesta
{
    public class Respuesta
    {
        public int codigo { get;set; }
        public string respuesta { get;set; }
        public object datos { get;set; }
    }
}

CRS/Controllers/HomeController.cs
using CRS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRS/Controllers/SegUsuariosController.cs
using CRS.Interfaces;
using CRS.Models.Respuesta;
using CRS.Utilitarios;
//using DCONTEXCRS.DbContex;
using DCONTEXCRS.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace CRS.Controllers
{
    public class SegUsuariosController : Controller
    {
        private readonly IJwtClass _jwtClass;
        private readonly ISegUsuariosDAL _segUsuarios;

        public SegUsuariosController(IJwtClass jwtClass, ISegUsuariosDAL segUsuarios)
        {
            this._jwtClass = jwtClass;
            this._segUsuarios = segUsuarios;
        }

        Respuesta respuesta = new Respuesta();
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("SegUsuarios/login")]
        public async Task<dynamic> login(string usuario, string contraseña, string role)
        {
            var token = string.Empty;
            bool login = false;
            try
            {
                login = await _segUsuarios.Sesion(usuario, contraseña);

                if (login)
                {
                    token = _jwtClass.GenerateToken(usuario, role);
                    respuesta.codigo = 0;
                    respuesta.respuesta = "Correcto";
                }
                else
                {
                    respuesta.codigo = 1;
                    token = "Usuario o clave incorrecta";
                    respuesta.respuesta = "Incorrecto";
                }

                respuesta.datos = token;
            }
            catch (Exception ex)
            {
                respuesta.codigo = 2;
                respuesta.respuesta = ex.Message;
                throw new Exception(ex.Message);
            }
            return respuesta;
        }

    }
}

CRS/Views/Home/Index.cshtml
<html>
<head>
    <link rel="stylesheet" href="~/css/Menu/menu.css" />
</head>
<body>
    <div class="area"></div>
    <nav class="main-menu">
        <ul>
            <li>
                <a href="https://jbfarrow.com">
                    <i class="fa fa-home fa-2x"></i>
                    <span class="nav-text">
                        Community Dashboard
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="#">
                    <i class="fa fa-globe fa-2x"></i>
                    <span class="nav-text">
                        Global Surveyors
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="#">
                    <i class="fa fa-comments fa-2x"></i>
                    <span class="nav-text">
                        Group Hub Forums
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="#">
                    <i class="fa fa-camera-retro fa-2x"></i>
                    <span class="nav-text">
                        Survey Photos
                    </span>
                </a>

            </li>
            <li>
                <a href="#">
                    <i class="fa fa-film fa-2x"></i>
                    <span class="nav-text">
                        Surveying Tutorials
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-book fa-2x"></i>
                    <span class="nav-text">
                        Surveying Jobs
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-cogs fa-2x"></i>
                    <span class="nav-text">
                        Tools & Resources
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-map-marker fa-2x"></i>
                    <span class="nav-text">
                        Member Map
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-info fa-2x"></i>
                    <span class="nav-text">
                        Documentation
                    </span>
                </a>
            </li>
        </ul>

        <ul class="logout">
            <li>
                <a href="#">
                    <i class="fa fa-power-off fa-2x"></i>
                    <span class="nav-text">
                        Logout
                    </span>
                </a>
            </li>
        </ul>
    </nav>
</body>
</html>

CRS/Views/SegUsuarios/Create.cshtml
@model DCONTEXCRS.DbContex.SegUsuario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SegUsuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdUsusario" class="control-label"></label>
                <input asp-for="IdUsusario" class="form-control" />
                <span asp-validation-for="IdUsusario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdTipoUsuario" class="control-label"></label>
                <input asp-for="IdTipoUsuario" class="form-control" />
                <span asp-validation-for="IdTipoUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPersona" class="control-label"></label>
                <input asp-for="IdPersona" class="form-control" />
                <span asp-validation-for="IdPersona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ususario" class="control-label"></label>
                <input asp-for="Ususario" class="form-control" />
                <span asp-validation-for="Ususario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasena" class="control-label"></label>
                <input asp-for="Contrasena" class="form-control" />
                <span asp-validation-for="Contrasena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ip" class="control-label"></label>
                <input asp-for="Ip" class="form-control" />
                <span asp-validation-for="Ip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuarioRegistro" class="control-label"></label>
                <input asp-for="IdUsuarioRegistro" class="form-control" />
                <span asp-validation-for="IdUsuarioRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuarioActualizado" class="control-label"></label>
                <input asp-for="IdUsuarioActualizado" class="form-control" />
                <span asp-validation-for="IdUsuarioActualizado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaActualizado" class="control-label"></label>
                <input asp-for="FechaActualizado" class="form-control" />
                <span asp-validation-for="FechaActualizado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRS/Views/SegUsuarios/Delete.cshtml
@model DCONTEXCRS.DbContex.SegUsuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SegUsuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdTipoUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdTipoUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPersona)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ususario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ususario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuarioRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuarioRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuarioActualizado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuarioActualizado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaActualizado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaActualizado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdUsusario" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRS/Views/SegUsuarios/Details.cshtml
@model DCONTEXCRS.DbContex.SegUsuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SegUsuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdTipoUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdTipoUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPersona)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ususario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ususario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuarioRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuarioRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuarioActualizado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuarioActualizado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaActualizado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaActualizado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdUsusario">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CRS/Views/SegUsuarios/Edit.cshtml
@model DCONTEXCRS.DbContex.SegUsuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SegUsuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdUsusario" />
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdTipoUsuario" class="control-label"></label>
                <input asp-for="IdTipoUsuario" class="form-control" />
                <span asp-validation-for="IdTipoUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPersona" class="control-label"></label>
                <input asp-for="IdPersona" class="form-control" />
                <span asp-validation-for="IdPersona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ususario" class="control-label"></label>
                <input asp-for="Ususario" class="form-control" />
                <span asp-validation-for="Ususario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasena" class="control-label"></label>
                <input asp-for="Contrasena" class="form-control" />
                <span asp-validation-for="Contrasena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ip" class="control-label"></label>
                <input asp-for="Ip" class="form-control" />
                <span asp-validation-for="Ip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuarioRegistro" class="control-label"></label>
                <input asp-for="IdUsuarioRegistro" class="form-control" />
                <span asp-validation-for="IdUsuarioRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuarioActualizado" class="control-label"></label>
                <input asp-for="IdUsuarioActualizado" class="form-control" />
                <span asp-validation-for="IdUsuarioActualizado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaActualizado" class="control-label"></label>
                <input asp-for="FechaActualizado" class="form-control" />
                <span asp-validation-for="FechaActualizado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRS/Views/SegUsuarios/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>
   
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
@*    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">*@
@*
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>*@
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="~/lib/sweetalert2/css/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Seguridad/iniciosesion.css" />
</head>

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form>
        <h3>Inicio</h3>

        <label for="username">Usuario</label>
        <input type="text" placeholder="usuario" id="usuario">

        <label for="password">Contraseña</label>
        <input type="password" placeholder="contraseña" id="contrasena">

        <button id="idsesion">Inicio</button>
       @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>*@
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>

    <script src="js/login/login.js"></script>
</body>
</html>

CRS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SegUsuarios" asp-action="Index">USUARIO</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>